export const PICX_REPO_NAME = 'xfxx2022/github-img'
export const INIT_REPO_NAME = 'github-img'
export const INIT_REPO_DESC = 'github images hosting repository'
export const INIT_REPO_BARNCH = 'master'
export const PICX_UPLOAD_IMG_DESC = 'Upload image(https://github.com/xfxx2022/github-img)'
export const PICX_UPLOAD_IMGS_DESC = 'Upload images(https://github.com/xfxx2022/github-img)'
export const PICX_DEL_IMG_DESC = 'Delete image(https://github.com/xfxx2022/github-img)'
